name: Run get_stock_data Python script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Change to the version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file

      - name: Set up environment variable
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Run get_stock_data.py
        run: python get_stock_data.py

      - name: Decode and Save Google Cloud Credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" | base64 --decode > $HOME/google-credentials.json
      
      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=$HOME/google-credentials.json

      - name: Run update_database script
        run: python update_database.py


