name: Run get_stock_data Python script

on:
  schedule:
    - cron: '30 23 * * *'  # Runs daily at 11:30 PM UTC+2, which is 9:30 PM UTC
  workflow_dispatch:  # Optional: allows manual trigger from GitHub UI

jobs:
  combine_csvs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have a requirements.txt file

    - name: Decode and Save Google Cloud Credentials
      run: |
        echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" | base64 --decode > $HOME/google-credentials.json

    - name: Authenticate with Google Cloud
      run: gcloud auth activate-service-account --key-file=$HOME/google-credentials.json

    - name: Set environment variable for Python
      run: echo "GOOGLE_CREDENTIALS_JSON=$HOME/google-credentials.json" >> $GITHUB_ENV

    - name: Set environment variable for API_KEY
      run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

    - name: Check if combine_csvs has already run
      id: check_marker
      run: |
        if [ -f "$GITHUB_WORKSPACE/combine_csvs_successful.txt" ]; then
          echo "Marker exists, skipping combine_csvs job"
          exit 0  # Skip the job if the file exists
        else
          echo "No marker file found, proceeding with combine_csvs"
        fi

    - name: Run combine_csvs script
      if: steps.check_marker.outcome != 'success'  # Only run if the previous step did not exit
      run: |
        python combine_csvs.py  # Run the combine CSV script
        # Create the marker file to indicate script completion
        echo "combine_csvs completed successfully" > $GITHUB_WORKSPACE/combine_csvs_successful.txt

    - name: Commit marker file to repository
      if: steps.check_marker.outcome != 'success'  # Only run this if the file was created
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add $GITHUB_WORKSPACE/combine_csvs_successful.txt
        git commit -m "Add marker file to indicate combine_csvs completion"
        git push https://github.com/${{ github.repository }} HEAD:${{ github.ref }}

  update_database:
    runs-on: ubuntu-latest
    needs: combine_csvs  # Make sure this job runs after combine_csvs (if it runs)
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have a requirements.txt file

    - name: Decode and Save Google Cloud Credentials
      run: |
        echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" | base64 --decode > $HOME/google-credentials.json

    - name: Authenticate with Google Cloud
      run: gcloud auth activate-service-account --key-file=$HOME/google-credentials.json

    - name: Set environment variable for Python
      run: echo "GOOGLE_CREDENTIALS_JSON=$HOME/google-credentials.json" >> $GITHUB_ENV

    - name: Set environment variable for API_KEY
      run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

    - name: Run update_database script
      run: python update_database.py
